// THIS IS AN AUTO-GENERATED FILE, MODIFICATIONS IN THIS FILE WILL NOT BE PRESERVED

#if !defined(PROJECT_SETTINGS_H_)
#define PROJECT_SETTINGS_H_

char* WINDOW_TITLE = "Software Rasterizer";
u32 WINDOW_WIDTH = 1280;
u32 WINDOW_HEIGHT = 720;
bool WINDOW_RESIZABLE = 0;
char* DLL_FILE_NAME = "SoftwareRasterizer.dll";
u32 FPS_TARGET = 60;

#endif
